### ISSUE TITLE
return value from Swift to JavaScript

### ISSUE THREAD

**Issue by andrey-serdyuk** [ridi/WKJavaScriptController#1]
Hello.
Thanks for the plugin. It works perfect.

I'm trying to return a boolean value from swift to js like this:

Xprotocol.swift
func isNotification() -> JSBool;

Than I set the value like this:
func onEnableNotifications() {
        isNotifications.setValue(true, forKey: "")
    }
    
    func onDisableNotifications() {
        isNotifications.setValue(false, forKey: "")
    }
    
    func isNotification() -> JSBool {
        return isNotifications;
    }

At the runtime a receive the following warning:
Can not receive native return in JavaScript, so it was excluded. (selector: isNotification)

How can I fix it?
Thanks!

**Comment by DavinAhn** [comment]
Hi, @andretmn.
Thanks for using.

Unfortunately, the feature(return a boolean value from swift to js) is not yet supported.
This is due to structural limitations. but I am trying to solve it in various ways.
It will take some time. but I'll let you know when I resolve.

Thanks!

**Comment by andrey-serdyuk** [comment]
Can you suggest another plugin?

**Comment by DavinAhn** [comment]
I suggest [PhoneGap](http://phonegap.com).
(However, this is much heavier and more complex than WKJavaScriptController.)

**Comment by tapashmpl** [comment]
@DavinAhn @namenu  I am returning value from Swift to JavaScript like below:
func getAccessToken() -> String? {
        return Manager.shared.accessToken
    }

**Comment by DavinAhn** [comment]
Since the return value can only be received with Promise, show us JS code.

**Comment by tapashmpl** [comment]
@DavinAhn See I have not written any JS code. Without the JS code, it was working previously. Please let me know what's needs to be done from my side so that this issue could be fixed.
Thanks
