### ISSUE TITLE
webView remote url??

### ISSUE THREAD

**Issue by Gjworks** [ridi/WKJavaScriptController#2]
What if WebView is a web view for a non-local WebApp? (No hybrid)

`let urlWithSharp = "https://mysite"
let url = NSURL(string: urlWithSharp)
let request = NSURLRequest(url: url! as URL)`

**Comment by DavinAhn** [comment]
@gjworks 
You can use WKJavaScriptController whether you are local or remote.
Read the [README](https://github.com/ridi/WKJavaScriptController#usage) to see what to do.
