### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by alyona-bachurina** [ridi/WKJavaScriptController#3]
Hello!
It looks like  xcode9.3 does not building the pod, because of this piece of code: (WKJavaScriptController, line 288)
   ```
        let imp = method_getImplementation(method)
        if imp == nil { // Always false...?
            return
        }
```
        
method_getImplementation does not accept optional.

**Comment by DavinAhn** [comment]
Hi, @alyona-bachurina.
Try again with WKJavaScriptController 1.1.9.
