### ISSUE TITLE
Using with @escaping

### ISSUE THREAD

**Issue by gabrielsousaleal** [ridi/WKJavaScriptController#7]
Sometimes I need to use some swift function that needs a completion (@escaping), as I'm running a DispatchQueue.main.async.

example:

    func getGeolocation() -> String {
        var params: [String: AnyObject] = [:]
        let service = ServicoGeolocation()
        service.execute(showAlertPermission: true) { (location, error) in
            params = [
                "latitude": location.coordinate.latitude,
                "longitude": location.coordinate.longitude,
                "accuracy": location.horizontalAccuracy,
                "timestamp": location.timestamp.description
                ] as [String : AnyObject]
        }
        return params.description
    }

In this case I will always have the return [:] in javascript. Is there a way to pass this completion to javascript? Like:

@objc protocol JavaScriptProtocol {
    func getGeolocation(completion: @escaping(String) -> Void)
}

Or make the return happen just after service.execute()?

**Comment by DavinAhn** [comment]
[WKScriptMessage supports](https://developer.apple.com/documentation/webkit/wkscriptmessage/1417901-body) only `NSNumber`, `NSString`, `NSDate`, `NSArray`, `NSDictionary`, and `NSNull` types, so closures cannot be used as parameters.

But, With `DispatchGroup` you can do whatever you want.

```swift
@objc protocol JavaScriptProtocol {
    func getGeolocation() -> String
}

class SomeClass {
    private let group = DispatchGroup()

    ...
}

extension SomeClass: JavaScriptProtocol {
    func getGeolocation() -> String {
        var params: [String: AnyObject] = [:]
        let service = ServicoGeolocation()

        group.enter()
        service.execute(showAlertPermission: true) { (location, error) in
            params = [
                "latitude": location.coordinate.latitude,
                "longitude": location.coordinate.longitude,
                "accuracy": location.horizontalAccuracy,
                "timestamp": location.timestamp.description
            ] as [String : AnyObject]
            group.leave()
        }
        group.wait()

        return params.description
    }
}
```

Unfortunately, app will freeze if `getGeolocation` is being called on UI thread.

It need to modify `WKJavaScriptController` to call `getGeolocation` from another thread, so please try it and let me know.

**Comment by gabrielsousaleal** [comment]
yes, it freezes :(

basically .execute() asks for geolocation permission and the last coordinate, I think this should be executed in the main thread

**Comment by DavinAhn** [comment]
Ok, I will modify WKJavaScriptController.

**Comment by gabrielsousaleal** [comment]
Thank you so much! You will save me haha

**Comment by DavinAhn** [comment]
Retry after update.

```swift
@objc protocol JavaScriptProtocol {
    func getGeolocation() -> String
}

class SomeClass {
    private let group = DispatchGroup()

    ...
}

extension SomeClass: JavaScriptProtocol {
    func getGeolocation() -> String {
        var params: [String: AnyObject] = [:]
        let service = ServicoGeolocation()

        group.enter()
        DispatchQueue.main.async {
            service.execute(showAlertPermission: true) { (location, error) in
                params = [
                    "latitude": location.coordinate.latitude,
                    "longitude": location.coordinate.longitude,
                    "accuracy": location.horizontalAccuracy,
                    "timestamp": location.timestamp.description
                ] as [String : AnyObject]
                group.leave()
            }
        }
        group.wait()

        return params.description
    }
}
```

**Comment by gabrielsousaleal** [comment]
app no ​​longer freezes, but i get this error in javascript:

Error: Callback timeout. (id: df94e21da69b8e628ce22002a33d14e9)
user-script:1:21:40
runTask — polyfills-es2015.2b6a2f856658da0571b3.js:1:2969
invokeTask — polyfills-es2015.2b6a2f856658da0571b3.js:1:8607
(função anônima) — polyfills-es2015.2b6a2f856658da0571b3.js:1:31986

**Comment by DavinAhn** [comment]
How did you call the js bridge?

**Comment by gabrielsousaleal** [comment]
let a = await native.getGeolocation

using safari inspect console

**Comment by DavinAhn** [comment]
Ah... permission alert...

add code below.
```swift
webView.javaScriptController?.callbackTimeout = TimeInterval.infinity
```

**Comment by DavinAhn** [comment]
Sorry... can't use `TimeInterval.infinity`.
Set time long enough.

**Comment by gabrielsousaleal** [comment]
This worked! Thank you so much!!
