### ISSUE TITLE
Function without parameters with ()

### ISSUE THREAD

**Issue by gabrielsousaleal** [ridi/WKJavaScriptController#8]
Is there a way to call a function in JS that has no parameter like this:

native.function()

instead

let a = await native.function

(I would need to keep the android default, which is native.function())

**Comment by DavinAhn** [comment]
Did you fix it yourself?

**Comment by gabrielsousaleal** [comment]
Yes! I just delete the readOnlyProperties logic in the bridgeScript() function. Thanks for answering!

**Comment by DavinAhn** [comment]
Good...! I'll add an option soon.
Thanks for good point.
